# by Manper 20250520

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-airpifanctrl
PKG_VERSION:=1.2
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Manper

LUCI_TITLE:=LuCI support for AirPi fan control
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+kmod-airpi-gpio-fan

include $(TOPDIR)/feeds/luci/luci.mk
